title: Madeeha Umar # your name (or website title) here
logo: "/images/20230225_141936.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I love data. I am a data analyst focusing to enhance my analytical skills and use my problem solving nature to help businesses to grow faster.
  <br> <br>
  My strong communication skills along with my technical skills in Microsoft Excel, SQL, Tableau allow me to transform data into impactful insights that lead to the strong business decisions. <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
