title: Madeeha Umar # your name (or website title) here
logo: "/images/Madeeha 2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data analyst and I love data.
  <br>
  I love to help businesses with myy analytical skills and problem solving nature to grow faster.
  <br> <br>
  With my strong communication & powerful technical skills in SQL, Tableau and Excel, I aim to help businesses to transform data into impactful insights.
  This analysis supports to draw meaningful conclusions & make informed business decisions. <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
